### ISSUE TITLE
XML parameter error

### ISSUE THREAD

**Issue by HealthyPear** [ranieremenezes/easyfermi#49]
Whenever I try to analyze any source I get the following error,

```
Parameter::extractDomData:
In the XML description of parameter norm, An attempt has been made to set the parameter value outside of the specified bounds.
Traceback (most recent call last):
  File "/Users/michele/Applications/easyFermi/src/easyfermi/easyfermi.py", line 116, in run_gtsetup
    ui.gta.setup()
  File "/Users/michele/Applications/miniforge3/envs/easyfermi/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1090, in setup
    self._create_likelihood()
  File "/Users/michele/Applications/miniforge3/envs/easyfermi/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1117, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/Users/michele/Applications/miniforge3/envs/easyfermi/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5473, in _create_binned_analysis
    self._like = BinnedAnalysis(binnedData=self._obs,
  File "/Users/michele/Applications/miniforge3/envs/easyfermi/lib/python3.9/site-packages/fermipy/gtutils.py", line 644, in __init__
    self.logLike.readXml(srcModel, _funcFactory, False, True, False)
  File "/Users/michele/Applications/miniforge3/envs/easyfermi/lib/python3.9/site-packages/fermitools/pyLikelihood.py", line 12133, in readXml
    return _pyLikelihood.BinnedLikelihood_readXml(self, xmlFile, funcFactory, requireExposure, addPointSources, loadMaps)
RuntimeError: Parameter::extractDomData:
In the XML description of parameter norm, An attempt has been made to set the parameter value outside of the specified bounds.
```

The current details about my system are as follows,

```
macos Big Sur 11.7.10
MacBook Pro (Retina, 13-inch, Early 2015)
easyfermi                 2.0.9.dev0+g034d5b3.d20240227
fermipy                   v1.2
fermitools                2.2.0
fermitools-data           0.18
```

**Comment by ranieremenezes** [comment]
Unfortunately this issue for macOS is beyond our reach. Could you please move this issue to the [fermipy repository](https://github.com/fermiPy/fermipy/issues)?

**Comment by HealthyPear** [comment]
Sure, but I think it would be better to notify (e.g. in the docs) that this is a known issue...
